version: "2"

services:

  db:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - ./volumes/db/var/lib/mysql:/var/lib/mysql
      - ./volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    env_file: .env

  app:
    build:
      context: app
    restart: unless-stopped
    volumes:
      - ./volumes/app/mattermost/config:/mattermost/config:rw
      - ./volumes/app/mattermost/data:/mattermost/data:rw
      - ./volumes/app/mattermost/logs:/mattermost/logs:rw
      - /etc/localtime:/etc/localtime:ro
    env_file: .env

  web:
    build: web
    ports:
      - "${WEB_PORT}:80"
    restart: unless-stopped
    volumes:
      - ./volumes/web/cert:/cert:ro
      - /etc/localtime:/etc/localtime:ro
    env_file: .env
  bot:
    image: yulapshun/mattermost-cugcbot:latest
    restart: unless-stopped
    volumes:
      - ./volumes/bot/data:/root/cugc/data
    env_file: .env
    logging:
      driver: "json-file"
      options:
        max-size: "20M"
        max-file: "10"
