version: "2"

services:

  db:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - ./volumes/db/var/lib/mysql:/var/lib/mysql
      - ./volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_USER=mmuser
      - MYSQL_PASSWORD=mmuser_password
      - MYSQL_DATABASE=mattermost

  app:
    build:
      context: app
    restart: unless-stopped
    volumes:
      - ./volumes/app/mattermost/config:/mattermost/config:rw
      - ./volumes/app/mattermost/data:/mattermost/data:rw
      - ./volumes/app/mattermost/logs:/mattermost/logs:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MM_USERNAME=mmuser
      - MM_PASSWORD=mmuser_password
      - MM_DBNAME=mattermost
      - DB_HOST=db
      - DB_PORT_NUMBER=3306
      - MM_SQLSETTINGS_DRIVERNAME=mysql
      - MM_SQLSETTINGS_DATASOURCE=mmuser:mmuser_password@tcp(db:3306)/mattermost?charset=utf8mb4,utf8&readTimeout=30s&writeTimeout=30s

  web:
    build: web
    ports:
      - "17329:80"
    restart: unless-stopped
    volumes:
      - ./volumes/web/cert:/cert:ro
      - /etc/localtime:/etc/localtime:ro
  bot:
    image: yulapshun/mattermost-cugcbot:latest
    restart: unless-stopped
    volumes:
      - ./mattermost-cugcbot/uwsgi.ini:/root/uwsgi.ini
      - ./mattermost-cugcbot/config.ini:/root/config.ini
      - ./mattermost-cugcbot/cugc:/root/cugc/
    logging:
      driver: "json-file"
      options:
        max-size: "20M"
        max-file: "10"
    command: uwsgi --ini uwsgi.ini
